//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoxOne.Web {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FoxOneTips {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FoxOneTips() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FoxOne.Web.FoxOneTips", typeof(FoxOneTips).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 所有页面.
        /// </summary>
        internal static string AllPage {
            get {
                return ResourceManager.GetString("AllPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 组件编辑器.
        /// </summary>
        internal static string Component_Editor {
            get {
                return ResourceManager.GetString("Component_Editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 控件ID：{0} 重复.
        /// </summary>
        internal static string Ctrl_Id_Repeat {
            get {
                return ResourceManager.GetString("Ctrl_Id_Repeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 控件ID：{0} 不存在.
        /// </summary>
        internal static string Ctrl_Not_Found {
            get {
                return ResourceManager.GetString("Ctrl_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数据源返回0行数据.
        /// </summary>
        internal static string DataSource_Return_Empty {
            get {
                return ResourceManager.GetString("DataSource_Return_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 部门名称已存在.
        /// </summary>
        internal static string Department_Name_Already_In_Use {
            get {
                return ResourceManager.GetString("Department_Name_Already_In_Use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 非法操作.
        /// </summary>
        internal static string InValid_Operation {
            get {
                return ResourceManager.GetString("InValid_Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 原始密码错误.
        /// </summary>
        internal static string Invalid_Original_Password {
            get {
                return ResourceManager.GetString("Invalid_Original_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无效的验证码.
        /// </summary>
        internal static string InValid_Phone_ValidCode {
            get {
                return ResourceManager.GetString("InValid_Phone_ValidCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无效的用户名或密码.
        /// </summary>
        internal static string InValid_User_Or_Password {
            get {
                return ResourceManager.GetString("InValid_User_Or_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 手机号已注册.
        /// </summary>
        internal static string LoginId_Or_MobilePhone_Alerady_Exist {
            get {
                return ResourceManager.GetString("LoginId_Or_MobilePhone_Alerady_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登 录.
        /// </summary>
        internal static string LogOn {
            get {
                return ResourceManager.GetString("LogOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 需要为控件：{0} 指定数据源.
        /// </summary>
        internal static string Need_DataSource {
            get {
                return ResourceManager.GetString("Need_DataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 控件：{0} 需要继承自NoPagerListControlBase.
        /// </summary>
        internal static string Need_To_Be_NoPagerListControlBase {
            get {
                return ResourceManager.GetString("Need_To_Be_NoPagerListControlBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 控件：{0} 不是Tree控件.
        /// </summary>
        internal static string Need_To_Be_Tree {
            get {
                return ResourceManager.GetString("Need_To_Be_Tree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新密码与确认密码不一致.
        /// </summary>
        internal static string NewPassword_NotEqual_ConfirmPassword {
            get {
                return ResourceManager.GetString("NewPassword_NotEqual_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当前操作只支持Table组件.
        /// </summary>
        internal static string Only_Suppost_Table_Ctrl {
            get {
                return ResourceManager.GetString("Only_Suppost_Table_Ctrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 参数：&apos;{0}&apos; 不能为空.
        /// </summary>
        internal static string Parameter_Not_Found {
            get {
                return ResourceManager.GetString("Parameter_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密码.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密码不能为空.
        /// </summary>
        internal static string PassWord_Required {
            get {
                return ResourceManager.GetString("PassWord_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 手机号不存在.
        /// </summary>
        internal static string Phone_Not_Exist {
            get {
                return ResourceManager.GetString("Phone_Not_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 该角色已存在！.
        /// </summary>
        internal static string Role_Alerady_Exist {
            get {
                return ResourceManager.GetString("Role_Alerady_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SqlId：&apos;{0}&apos; 不存在.
        /// </summary>
        internal static string SqlId_Not_Found {
            get {
                return ResourceManager.GetString("SqlId_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 树型菜单.
        /// </summary>
        internal static string TreeMenu {
            get {
                return ResourceManager.GetString("TreeMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户名不能为空.
        /// </summary>
        internal static string User_Name_Required {
            get {
                return ResourceManager.GetString("User_Name_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户：&apos;{0}&apos;  不存在.
        /// </summary>
        internal static string User_Not_Found {
            get {
                return ResourceManager.GetString("User_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 账号.
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
    }
}
